org: yeukfei05
app: multivendor-api
service: multivendor-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  apiName: multivendor-api-dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    # USER_AWS_ACCESS_KEY_ID: ${params:USER_AWS_ACCESS_KEY_ID}
    # USER_AWS_SECRET_ACCESS_KEY: ${params:USER_AWS_SECRET_ACCESS_KEY}
    # DATABASE_URL_DEV: ${param:DATABASE_URL_DEV}
    # DATABASE_URL: ${param:DATABASE_URL}
  apiGateway:
    shouldStartNameWithService: true
    description: multivendor api dev
  lambdaHashingVersion: 20201221

functions:
  graphqlHandler:
    handler: src/graphql/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline