name: Deploy master branch

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # USER_AWS_ACCESS_KEY_ID: ${{ secrets.USER_AWS_ACCESS_KEY_ID }}
          # USER_AWS_SECRET_ACCESS_KEY: ${{ secrets.USER_AWS_SECRET_ACCESS_KEY }}
